import {env} from 'cloudflare:workers';
import {createPublicClient,recoverMessageAddress} from 'viem';
import {robinhood,contracts} from '@/lib/config';
import {agentPassportAbi} from '@/lib/abis';
import {agentStore} from '@/lib/agent-store';
import {validateAgent} from '@/lib/agent-spec';
import {unseal} from '@/lib/vault';
import {trainingFields,trainingRequest} from '@/lib/training';
import {canonicalMessage,actionId} from '@/lib/message';
import {serverRobinhoodTransport} from '@/lib/server-rpc';
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const client=createPublicClient({chain:robinhood,transport:serverRobinhoodTransport(10000)});
export async function POST(request:Request){const owner=request.headers.get('oai-authenticated-user-id');if(!owner)return reply({error:'Sign in first.'},401);if(request.headers.get('origin')!==new URL(request.url).origin)return reply({error:'Origin mismatch.'},403);let runId:string|undefined;const db=agentStore();try{const raw=await request.text();if(raw.length>5000)return reply({error:'Request too large.'},413);const x=JSON.parse(raw);const now=Math.floor(Date.now()/1000);if(typeof x.id!=='string'||!Number.isSafeInteger(x.revision)||typeof x.file!=='string'||!/^file-[a-zA-Z0-9_-]{1,100}$/.test(x.file)||typeof x.nonce!=='string'||!/^[a-f0-9-]{36}$/.test(x.nonce)||!Number.isSafeInteger(x.deadline)||x.deadline<=now||x.deadline>now+120||typeof x.signature!=='string'||!/^0x[a-fA-F0-9]{130}$/.test(x.signature))return reply({error:'Invalid signed training request.'},400);
 const row=await db.prepare('SELECT spec,revision FROM agent_configs WHERE id=? AND owner=?').bind(x.id,owner).first();if(!row||row.revision!==x.revision)return reply({error:'Save and reload this agent first.'},409);const spec=validateAgent(JSON.parse(String(row.spec)));if(spec.provider!=='OpenAI')return reply({error:'Training submission currently supports eligible OpenAI accounts only.'},400);const c=await db.prepare('SELECT ciphertext FROM provider_credentials WHERE id=? AND owner=?').bind(owner+':OpenAI',owner).first();if(!c)return reply({error:'Connect OpenAI first.'},400);const fields=trainingFields(x.id,x.revision,spec.passportId,x.nonce,x.deadline,x.file);const signer=await recoverMessageAddress({message:canonicalMessage(fields),signature:x.signature});const base={address:contracts[4663].agentPassport,abi:agentPassportAbi} as const;const agent=await client.readContract({...base,functionName:'agentOf',args:[BigInt(spec.passportId)]});if(agent.toLowerCase()!==signer.toLowerCase()||!await client.readContract({...base,functionName:'verifyAuthority',args:[BigInt(spec.passportId),actionId('TRAIN_AGENT'),0n]}))return reply({error:'Agent signature and TRAIN_AGENT authority required.'},403);const nonce=await db.prepare('INSERT OR IGNORE INTO used_nonces (nonce_key,expires_at) VALUES (?,?)').bind('training:'+owner+':'+x.nonce,x.deadline).run();if(nonce.meta.changes!==1)return reply({error:'Already submitted. Check run history and provider dashboard.'},409);
 runId=crypto.randomUUID();const r=await db.prepare("INSERT INTO agent_runs (id,owner,agent_id,revision,status,output,created_at) SELECT ?,?,?,?,'training_submitting','',? WHERE (SELECT count(*) FROM agent_runs WHERE owner=? AND status LIKE 'training%' AND created_at>?)<3").bind(runId,owner,x.id,x.revision,Date.now(),owner,Date.now()-86400000).run();if(r.meta.changes!==1)return reply({error:'Training limit reached: three submissions per day.'},429);const key=await unseal((env as unknown as Record<string,string>).AGENT_VAULT_KEY??'',owner,'OpenAI',String(c.ciphertext));const job=await trainingRequest(key,spec.model,x.file);await db.prepare("UPDATE agent_runs SET status='training_submitted',output=? WHERE id=? AND owner=?").bind(JSON.stringify(job),runId,owner).run();return reply({runId,job});
 }catch{if(runId)try{await db.prepare("UPDATE agent_runs SET status='training_unknown',output=? WHERE id=? AND owner=?").bind('Check the provider dashboard before submitting again; the job may have been accepted.',runId,owner).run();}catch{}return reply({error:'Training failed or outcome unknown. Check the OpenAI dashboard for account eligibility and existing jobs before retrying.'},503);}}
