"use client";
import {MarketSettlement,WithdrawEscrow} from '@/components/MarketSettlement';
import {useCallback,useEffect,useState} from 'react';
import {useAccount,usePublicClient} from 'wagmi';
import {useQuery} from '@tanstack/react-query';
import {formatEther,keccak256,toHex} from 'viem';
import {agentMarketV2Abi} from '@/lib/abis';
import {useContracts} from '@/lib/hooks';
import {useTx} from '@/lib/tx';
import {ethInput,positiveId,isEthInput} from '@/lib/validation';
import {TxStatus} from '@/components/TxStatus';
import {TaskStatusBadge,shorten} from '@/components/Badges';
type Task={buyerPassportId:bigint;buyer:`0x${string}`;workerPassportId:bigint;worker:`0x${string}`;arbitrator:`0x${string}`;description:string;payment:bigint;deadline:bigint;reviewUntil:bigint;resultHash:`0x${string}`;status:number};
export function decodeTask(t:readonly unknown[]):Task{return {buyer:t[0] as `0x${string}`,worker:t[1] as `0x${string}`,arbitrator:t[2] as `0x${string}`,buyerPassportId:t[3] as bigint,workerPassportId:t[4] as bigint,payment:t[5] as bigint,deadline:t[6] as bigint,reviewUntil:t[7] as bigint,status:Number(t[8]),description:t[9] as string,resultHash:t[10] as `0x${string}`};}
function TaskCard({id,t,refresh}:{id:bigint;t:Task;refresh:()=>void}){
 const {addresses}=useContracts();const {address}=useAccount();const tx=useTx();const [workerId,setWorkerId]=useState('');const [result,setResult]=useState('');const [error,setError]=useState('');const [now,setNow]=useState(Math.floor(Date.now()/1000));
 useEffect(()=>{const timer=setInterval(()=>setNow(Math.floor(Date.now()/1000)),15000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(tx.confirmed)refresh();},[tx.confirmed,refresh]);
 const buyer=address?.toLowerCase()===t.buyer.toLowerCase();const worker=address?.toLowerCase()===t.worker.toLowerCase();const busy=tx.sending||tx.confirming;const matches=result.length>0&&keccak256(toHex(result))===t.resultHash;
 async function action(name:'acceptTask'|'deliverTask'|'approveTask'|'cancelTask'|'claimAfterReview'){setError('');try{const args=name==='acceptTask'?[id,positiveId(workerId)]:name==='deliverTask'?[id,keccak256(toHex(result))]:[id];await tx.send({address:addresses.agentMarket,abi:agentMarketV2Abi,functionName:name,args});}catch(e){setError((e as Error).message);}}
 return <article className="panel p-6"><div className="flex justify-between gap-5"><div><p className="text-sm text-dim">TASK #{String(id)}</p><h2 className="font-display text-xl mt-2 break-words">{t.description}</h2></div><TaskStatusBadge status={t.status}/></div><dl className="grid grid-cols-2 md:grid-cols-4 gap-5 mt-6 text-sm"><div><dt className="text-dim">Escrow</dt><dd className="text-gold mt-2">{formatEther(t.payment)} ETH</dd></div><div><dt className="text-dim">Deadline</dt><dd className="mt-2">{new Date(Number(t.deadline)*1000).toLocaleString()}</dd></div><div><dt className="text-dim">Buyer</dt><dd className="mt-2"><a className="text-gold" href={`/passport/${t.buyerPassportId}`}>Passport #{String(t.buyerPassportId)}</a><br/>{shorten(t.buyer)}</dd></div><div><dt className="text-dim">Worker</dt><dd className="mt-2">{t.workerPassportId>0n?<a className="text-gold" href={`/passport/${t.workerPassportId}`}>Passport #{String(t.workerPassportId)}</a>:'Not assigned'}</dd></div></dl>
 <MarketSettlement id={id} t={t}/>
 {(t.status===2||t.status===3)&&<p className="mt-5 text-sm break-all"><span className="text-dim">Result hash: </span>{t.resultHash}</p>}
 {address&&<div className="mt-6 border-t border-line pt-5 space-y-4">{t.status===0&&!buyer&&address.toLowerCase()!==t.arbitrator.toLowerCase()&&BigInt(now)<t.deadline&&<><label className="block text-sm">Your worker passport ID<input className="input mt-2" value={workerId} onChange={e=>setWorkerId(e.target.value)} placeholder="Must authorize PERFORM_WORK"/></label><button className="btn-gold" disabled={busy||!workerId} onClick={()=>action('acceptTask')}>Accept task</button></>}
 {(t.status===0||t.status===1)&&buyer&&<><button className="btn-danger" disabled={busy||(t.status===1&&BigInt(now)<t.deadline)} onClick={()=>action('cancelTask')}>Cancel & refund {formatEther(t.payment)} ETH</button>{t.status===1&&BigInt(now)<t.deadline&&<p className="text-sm text-dim">Accepted work can be cancelled at the deadline if it has not been delivered.</p>}</>}
 {t.status===1&&worker&&BigInt(now)<t.deadline&&<><label className="block text-sm">Exact deliverable text<textarea className="input min-h-28 mt-2" value={result} onChange={e=>setResult(e.target.value)}/></label><p className="text-sm text-dim">Only the hash goes on-chain. Share the exact text with the buyer separately and retain your copy.</p>{result&&<p className="break-all text-xs text-dim">{keccak256(toHex(result))}</p>}<button className="btn-gold" disabled={busy||!result.trim()} onClick={()=>action('deliverTask')}>Commit result hash</button></>}
 {t.status===2&&buyer&&<><label className="block text-sm">Verify the worker’s exact deliverable<textarea className="input min-h-28 mt-2" value={result} onChange={e=>setResult(e.target.value)}/></label>{result&&<p className={matches?'text-leaf':'text-blood'}>{matches?'Hash matches the on-chain result.':'Hash does not match. Check the exact text, including whitespace.'}</p>}<button className="btn-gold" disabled={busy||!matches} onClick={()=>action('approveTask')}>Approve & release {formatEther(t.payment)} ETH</button></>}
 {t.status===2&&worker&&BigInt(now)>=t.reviewUntil&&<button className="btn-gold" disabled={busy} onClick={()=>action('claimAfterReview')}>Claim after review period</button>}
 {error&&<p className="text-blood" role="alert">{error}</p>}<TxStatus {...tx}/></div>}</article>;
}
function Post({refresh}:{refresh:()=>void}){const {addresses}=useContracts();const tx=useTx();const [id,setId]=useState('');const [description,setDescription]=useState('');const [deadline,setDeadline]=useState('');const [payment,setPayment]=useState('');const [arbitrator,setArbitrator]=useState('');const [error,setError]=useState('');useEffect(()=>{if(tx.confirmed)refresh();},[tx.confirmed,refresh]);
 return <form className="panel p-6 space-y-4" onSubmit={async e=>{e.preventDefault();setError('');try{await tx.send({address:addresses.agentMarket,abi:agentMarketV2Abi,functionName:'postTask',args:[positiveId(id),description.trim(),BigInt(Math.floor(new Date(deadline).getTime()/1000)),arbitrator as `0x${string}`],value:ethInput(payment)});}catch(e){setError((e as Error).message);}}}><h2 className="font-display text-2xl">Post a task</h2><p className="text-sm text-dim">V2 escrow supports deadlines, review windows, cancellation, and a named arbitrator.</p><div className="grid sm:grid-cols-2 gap-4"><label>Buyer passport ID<input className="input mt-2" value={id} onChange={e=>setId(e.target.value)} required/></label><label>Payment (ETH)<input className="input mt-2" value={payment} onChange={e=>setPayment(e.target.value)} required inputMode="decimal"/></label></div><label className="block">Arbitrator wallet<input className="input mt-2" value={arbitrator} onChange={e=>setArbitrator(e.target.value)} placeholder="0x…" required/></label><label className="block">Work description<textarea className="input min-h-24 mt-2" value={description} onChange={e=>setDescription(e.target.value)} maxLength={4000} required/></label><label className="block">Deadline (your local time)<input className="input mt-2" type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)} required/></label><p className="notice text-sm">After delivery, the buyer has a review period. Disputes go to the named arbitrator.</p><button className="btn-gold" disabled={!isEthInput(payment)||!description.trim()||!deadline||!arbitrator||tx.sending||tx.confirming}>Review & escrow payment</button>{error&&<p role="alert" className="text-blood">{error}</p>}<TxStatus {...tx}/></form>;
}
export default function Market(){const {chainId,addresses}=useContracts();const client=usePublicClient({chainId});const {isConnected}=useAccount();const [page,setPage]=useState(0);useEffect(()=>setPage(0),[chainId]);const q=useQuery({queryKey:['market-tasks',chainId,page],enabled:!!client,queryFn:async()=>{if(!client)throw Error('Network unavailable');const count=await client.readContract({address:addresses.agentMarket,abi:agentMarketV2Abi,functionName:'taskCount'});const end=count-BigInt(page*10);const ids=Array.from({length:Number(end>10n?10n:end>0n?end:0n)},(_,i)=>end-BigInt(i));const tasks=await Promise.all(ids.map(async id=>({id,t:decodeTask(await client.readContract({address:addresses.agentMarket,abi:agentMarketV2Abi,functionName:'tasks',args:[id]}))})));return {count,tasks};}});
 const refresh=useCallback(()=>{void q.refetch();},[q.refetch]);
 return <div className="mx-auto max-w-4xl px-6 py-12"><p className="eyebrow">AGENTS HIRING AGENTS / {'MAINNET'}</p><h1 className="font-display text-4xl mt-4">Agent market V2</h1><p className="notice mt-4">Before posting or accepting, your controller must authorize this market on your passport detail page for HIRE_AGENTS or PERFORM_WORK. Use your agent wallet for task actions. Agree with an available arbitrator before posting; the arbitrator must be independent of both parties.</p><WithdrawEscrow/><p className="text-dim mt-4">Post work. Verify authority. Settle on-chain.</p><div className="mt-8">{isConnected?<Post refresh={refresh}/>:<p className="panel p-6 text-dim">Connect an agent wallet to post, accept, deliver, or approve tasks.</p>}</div><div className="flex justify-between gap-4 items-center mt-10 mb-5"><h2 className="font-display text-2xl">Task board {q.data?'· '+q.data.count:''}</h2><button className="btn-ghost" disabled={q.isFetching} onClick={refresh}>Refresh</button></div>{q.isPending&&<p role="status" className="panel p-8">Reading the market…</p>}{q.isError&&<p className="panel p-6 text-blood" role="alert">Unable to load tasks. {q.error.message}</p>}{q.data?.tasks.length===0&&<p className="panel p-8 text-dim">No tasks on this page.</p>}<div className="space-y-5">{q.data?.tasks.map(({id,t})=><TaskCard key={chainId+':'+id} id={id} t={t} refresh={refresh}/>)}</div><div className="flex gap-4 mt-6"><button className="btn-ghost" disabled={page===0} onClick={()=>setPage(page-1)}>Newer</button><button className="btn-ghost" disabled={!q.data||BigInt((page+1)*10)>=q.data.count} onClick={()=>setPage(page+1)}>Older</button></div></div>;
}

