"use client";
import {useState} from 'react';
import {useAccount,usePublicClient} from 'wagmi';
import {useQuery} from '@tanstack/react-query';
import {parseAbi,formatEther} from 'viem';
import {useContracts} from '@/lib/hooks';
import {useTx} from '@/lib/tx';
import {ethInput,positiveId,isEthInput} from '@/lib/validation';
import {TxStatus} from '@/components/TxStatus';
const abi=parseAbi(['function bookingCount() view returns (uint256)','function bookings(uint256) view returns (uint256 passportId,address agent,string destination,uint256 cost,uint64 bookedAt)','function bookTrip(uint256 passportId,string destination) payable returns (uint256)']);
export default function Travel(){const {chainId,addresses}=useContracts();const {isConnected}=useAccount();const client=usePublicClient({chainId});const tx=useTx();const [id,setId]=useState('');const [destination,setDestination]=useState('');const [amount,setAmount]=useState('');const [accepted,setAccepted]=useState(false);const [error,setError]=useState('');
 const q=useQuery({queryKey:['travel',chainId],enabled:!!client,queryFn:async()=>{if(!client)throw Error('Network unavailable');const count=await client.readContract({address:addresses.travelBooking,abi,functionName:'bookingCount'});const ids=Array.from({length:Number(count>10n?10n:count)},(_,i)=>count-BigInt(i));return Promise.all(ids.map(async id=>({id,booking:await client.readContract({address:addresses.travelBooking,abi,functionName:'bookings',args:[id]})})));}});
 return <div className="mx-auto max-w-4xl px-6 py-12"><p className="eyebrow">CONSUMER INTEGRATION</p><h1 className="font-display text-4xl mt-4">Travel contract</h1><p className="notice mt-6">Legacy V1 demonstration: this contract accepts V1 passports only. V2 passports cannot use it. This is a contract demonstration, not a travel service. It records a destination and accepts ETH. No flight or hotel is reserved, and the deployed contract has no refund or withdrawal method.</p><form className="panel p-6 mt-6 space-y-4" onSubmit={async e=>{e.preventDefault();setError('');try{await tx.send({address:addresses.travelBooking,abi,functionName:'bookTrip',args:[positiveId(id),destination.trim()],value:ethInput(amount)});}catch(e){setError((e as Error).message);}}}><label className="block">Legacy V1 passport ID<input className="input mt-2" value={id} onChange={e=>setId(e.target.value)} required/></label><label className="block">Destination reference<input className="input mt-2" value={destination} onChange={e=>setDestination(e.target.value)} required/></label><label className="block">ETH sent to contract<input className="input mt-2" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label className="flex items-start gap-3"><input type="checkbox" className="mt-1" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I understand this records a demo booking and the ETH cannot be refunded through this contract.</span></label><button className="btn-gold" disabled={!isConnected||!accepted||!isEthInput(amount)||tx.sending||tx.confirming}>Review demo transaction</button>{!isConnected&&<p className="text-dim">Connect the named agent wallet to submit.</p>}{error&&<p role="alert" className="text-blood">{error}</p>}<TxStatus {...tx}/></form><h2 className="font-display text-2xl mt-10 mb-5">Latest bookings</h2>{q.isPending&&<p>Loading…</p>}{q.isError&&<p className="text-blood">Could not read bookings. <button onClick={()=>q.refetch()}>Retry</button></p>}{q.isSuccess&&q.data.length===0&&<p className="panel p-6 text-dim">No bookings recorded.</p>}<div className="space-y-3">{q.data?.map(({id,booking})=><article className="panel p-5" key={String(id)}><strong>#{String(id)} · {booking[2]}</strong><p className="text-dim mt-2">Passport #{String(booking[0])} · {formatEther(booking[3])} ETH</p></article>)}</div></div>;
}
