"use client";
import {useAccount,usePublicClient,useBalance} from 'wagmi';
import {useQuery} from '@tanstack/react-query';
import {useContracts} from '@/lib/hooks';
import {fetchPassportIds,fetchPassports,effectiveStatus} from '@/lib/passport';
import {ConnectButton} from '@/components/ConnectButton';
import {shorten} from '@/components/Badges';
import {formatEther} from 'viem';
export default function Dashboard(){
 const {chainId,addresses}=useContracts();const {address}=useAccount();const client=usePublicClient({chainId});const balance=useBalance({address,chainId});
 const q=useQuery({queryKey:['dashboard',chainId,address],enabled:!!address&&!!client,queryFn:async()=>{if(!client)throw Error('Network unavailable');return fetchPassports(client,addresses.agentPassport,await fetchPassportIds(client,addresses.agentPassport));}});
 const mine=(q.data??[]).filter(p=>p.controller.toLowerCase()===address?.toLowerCase());const agents=(q.data??[]).filter(p=>p.agent.toLowerCase()===address?.toLowerCase());
 return <div className="mx-auto max-w-6xl px-6 py-12"><p className="eyebrow">YOUR WORKSPACE / {'MAINNET'}</p><div className="flex flex-wrap justify-between items-end gap-4 mt-4"><div><h1 className="font-display text-4xl">Agent dashboard</h1><p className="mt-3 text-dim">Issue identities. Manage authority. Follow your agents.</p></div><a className="btn-gold" href="/mint">Issue a passport ↗</a></div>{!address?<div className="panel p-10 mt-8"><h2 className="font-display text-2xl mb-3">Your agents start here.</h2><p className="text-dim mb-5">Connect your browser wallet to view the passports you control and those assigned to your address.</p><ConnectButton/></div>:<><div className="metrics"><div className="panel metric"><span className="text-dim">Controlled passports</span><strong>{q.isSuccess?mine.length:'—'}</strong></div><div className="panel metric"><span className="text-dim">Active passports</span><strong>{q.isSuccess?mine.filter(p=>effectiveStatus(p)==='Active').length:'—'}</strong></div><div className="panel metric"><span className="text-dim">Wallet balance</span><strong className="!text-xl">{balance.data?formatEther(balance.data.value).slice(0,12)+' ETH':'—'}</strong></div></div><div className="flex justify-between gap-4 mb-4"><h2 className="font-display text-2xl">Your passports</h2><button className="btn-ghost" disabled={q.isFetching} onClick={()=>q.refetch()}>Refresh</button></div>{q.isPending&&<p role="status" className="panel p-8">Reading your passports…</p>}{q.isError&&<p role="alert" className="panel p-8 text-blood">Unable to load passports. {q.error.message}</p>}{q.isSuccess&&(mine.length+agents.length===0?<div className="panel p-8"><h3 className="font-display text-xl">No passports for this wallet yet.</h3><p className="mt-2 text-dim">Issue your first passport to an agent address.</p></div>:<div className="panel table-scroll"><table className="data-table"><thead><tr><th>Passport</th><th>Agent</th><th>Your role</th><th>Status</th><th></th></tr></thead><tbody>{(q.data??[]).filter(p=>mine.includes(p)||agents.includes(p)).map(p=><tr key={String(p.id)}><td>#{String(p.id)} · {p.purpose}</td><td>{shorten(p.agent)}</td><td>{mine.includes(p)?'Controller':'Agent'}</td><td>{effectiveStatus(p)}</td><td><a className="text-gold" href={`/passport/${p.id}`}>Open ↗</a></td></tr>)}</tbody></table></div>)}</>}<div className="home-grid">{[['Registry','Browse every passport on the selected network.','/explore'],['Agent market','Post work or manage your agent’s tasks.','/market'],['Verify authority','Check a passport and test a signed API request.','/verify']].map(([title,body,href])=><a className="panel p-6" key={href} href={href}><h2 className="font-display text-xl">{title} ↗</h2><p className="mt-3 text-dim">{body}</p></a>)}</div></div>;
}
