"use client";
import {formatEther} from 'viem';
import {useAccount,useBalance} from 'wagmi';
import {contracts,explorerAddress} from '@/lib/config';
const wallet='0x096c89f8e8b872420cfc177964dc4d8880d64cee' as const;
const steps=[
 {title:'Issue or replace identity',body:'Issue a V2 passport to the agent wallet, or inspect a V1 identity and create its explicit V2 replacement.',links:[['/mint','Issue V2'],['/migrate','Upgrade V1']]},
 {title:'Run a real model request',body:'Save an agent, connect a provider key, grant RUN_AGENT, then sign a one-time execution from the named agent wallet.',links:[['/agents','Open Agent Studio']]},
 {title:'Complete escrow lifecycle',body:'Use independent buyer, worker, and arbitrator wallets to post, accept, deliver, dispute or approve, resolve, and withdraw.',links:[['/market','Open Market']]},
 {title:'Execute a reviewed swap',body:'Connect Uniswap, grant proposal and execution permissions, record the ETH amount through Passport, then review the router transaction.',links:[['/trade','Open Trade Studio']]},
] as const;
export default function Validate(){const {address}=useAccount();const balance=useBalance({address:wallet,chainId:4663});const match=address?.toLowerCase()===wallet;return <div className="mx-auto max-w-5xl px-6 py-12"><p className="eyebrow">LIVE VALIDATION / MAINNET</p><h1 className="font-display text-4xl mt-4">Finish the real-wallet checks.</h1><p className="text-dim mt-4 max-w-3xl">The deployed V2 bytecode passed the full lifecycle on a mainnet fork. This page organizes the remaining signatures that must come from wallets you control on the live chain.</p><section className="panel p-6 mt-8"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm text-dim">Primary wallet</p><p className="mt-2 break-all">{wallet}</p></div><div><p className="text-sm text-dim">Live balance</p><p className="mt-2">{balance.isPending?'Reading…':balance.isError?'Unavailable':formatEther(balance.data?.value??0n)+' ETH'}</p></div><div><p className="text-sm text-dim">Connected wallet</p><p className={match?'text-leaf mt-2':'text-gold mt-2'}>{address?(match?'Primary wallet connected':'Another wallet connected'):'Connect to sign'}</p></div></div></section><div className="grid md:grid-cols-2 gap-5 mt-6">{steps.map((s,i)=><section className="panel p-6" key={s.title}><p className="eyebrow">STEP {i+1}</p><h2 className="font-display text-2xl mt-3">{s.title}</h2><p className="text-dim mt-3 leading-relaxed">{s.body}</p><div className="flex flex-wrap gap-3 mt-5">{s.links.map(([href,label])=><a className="btn-ghost" href={href} key={href}>{label}</a>)}</div></section>)}</div><section className="notice mt-6"><p>Escrow cannot be honestly tested with one wallet: Market V2 prevents the buyer, worker, and arbitrator from collapsing into the same role. Use three independently controlled wallets and a tiny amount.</p><p className="mt-3">Contracts: <a className="text-gold" href={explorerAddress(4663,contracts[4663].agentPassport)} target="_blank" rel="noreferrer">Passport V2 ↗</a> · <a className="text-gold" href={explorerAddress(4663,contracts[4663].agentMarket)} target="_blank" rel="noreferrer">Market V2 ↗</a></p></section></div>}
