"use client";
import {AgentTraining} from './AgentTraining';
import {useEffect,useState} from 'react';
import {useAccount,useSignMessage} from 'wagmi';
import {executableProviders} from '@/lib/model-adapters';
import {runFields} from '@/lib/run-authorization';
import {canonicalMessage} from '@/lib/message';
export function AgentRunner({current,passportId,provider}:{current?:{id:string;revision:number};passportId:string;provider:string}){
 const {address}=useAccount();const {signMessageAsync}=useSignMessage();const [apiKey,setKey]=useState('');const [connected,setConnected]=useState<string[]>([]);const [prompt,setPrompt]=useState('');const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [runs,setRuns]=useState<Array<{id:string;status:string;output:string;created_at:number}>>([]);
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/agents/credentials'),fetch('/api/agents/run')]);if(a.ok)setConnected((await a.json() as {providers:{provider:string}[]}).providers.map((p:{provider:string})=>p.provider));if(b.ok)setRuns((await b.json() as {runs:typeof runs}).runs);}catch{setMessage('Could not refresh connections or run history.');}}
 useEffect(()=>{void load();},[]);
 async function connect(remove=false){setBusy(true);setMessage('');try{const r=await fetch('/api/agents/credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,apiKey,remove})});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error??'Request failed.');setKey('');setMessage(remove?'Provider key removed.':'Provider key saved encrypted. Its validity is checked on a run.');await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function run(){if(!current)return;setBusy(true);setMessage('');try{const fields=runFields(current.id,current.revision,passportId,crypto.randomUUID(),Math.floor(Date.now()/1000)+120,prompt);const signature=await signMessageAsync({message:canonicalMessage(fields)});const r=await fetch('/api/agents/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...current,prompt,nonce:fields.nonce,deadline:fields.deadline,signature})});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error??'Request failed.');setMessage('Run completed. Output is recorded below.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);await load();}}
 return <section className="panel p-5 space-y-4"><h2 className="font-display text-2xl">Connect and run</h2><p className="text-sm text-dim">Run the saved revision once with your selected model. Requires RUN_AGENT permission and the agent wallet signature. Chain context also requires READ_CHAIN. Output is text; trades and external actions are not executed.</p><p>{provider}: {connected.includes(provider)?'Key saved':'No key connected'}</p>{executableProviders.includes(provider as typeof executableProviders[number])?<><label className="block">Provider API key<input className="input mt-2" type="password" autoComplete="new-password" value={apiKey} onChange={e=>setKey(e.target.value)}/></label><p className="text-sm text-dim">Keys are encrypted in server storage and sent only to the selected provider. Never enter a wallet private key.</p><div className="flex gap-3"><button className="btn-ghost" disabled={busy||!apiKey} onClick={()=>connect()}>Save encrypted key</button><button className="btn-ghost" disabled={busy||!connected.includes(provider)} onClick={()=>connect(true)}>Remove key</button></div></>:<p className="notice">Custom endpoints need a reviewed adapter and are not executable yet.</p>}<label className="block">Task for this run<textarea className="input mt-2" maxLength={8000} value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><label className="flex gap-3"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I approve sending the saved instructions, task, and permitted chain context to {provider}. Provider API usage charges apply, with a 1,500 output-token cap per run. ETH passport budgets do not cap provider charges.</span></label><button className="btn-gold" disabled={busy||!current||!address||!consent||!prompt.trim()||!connected.includes(provider)} onClick={run}>{busy?'Working…':'Sign & run saved agent'}</button>{!current&&<p>Save an agent configuration first.</p>}<button className="btn-ghost" disabled={busy} onClick={load}>Refresh run history</button><AgentTraining current={current} passportId={passportId} provider={provider}/>{message&&<p role="status">{message}</p>}<div className="space-y-4">{runs.map(r=><article key={r.id} className="border-t border-line pt-4"><p className="text-sm text-dim">{r.status} · {new Date(r.created_at).toLocaleString()}</p><pre className="whitespace-pre-wrap break-words text-sm mt-2">{r.output||'No result recorded yet. If this remains pending, check provider usage before retrying.'}</pre></article>)}</div></section>;
}
