"use client";
import {useState} from 'react';
import {useAccount,useReadContract} from 'wagmi';
import {formatEther,keccak256,toHex,parseAbi} from 'viem';
import {agentMarketV2Abi} from '@/lib/abis';
import {useContracts} from '@/lib/hooks';
import {ethInput} from '@/lib/validation';
import {useTx} from '@/lib/tx';
import {TxStatus} from './TxStatus';
export function WithdrawEscrow(){const {address}=useAccount();const {chainId,addresses}=useContracts();const tx=useTx();const q=useReadContract({address:addresses.agentMarket,abi:parseAbi(['function claimable(address) view returns (uint256)']),functionName:'claimable',args:address?[address]:undefined,chainId,query:{enabled:!!address}});if(!address)return null;return <section className="panel p-6 mt-6 space-y-3"><h2 className="font-display text-2xl">Withdraw settled funds</h2><p>{q.isPending?'Reading balance…':q.isError?'Unable to read your balance.':formatEther(q.data??0n)+' ETH available'}</p><p className="text-sm text-dim">Approval, refund, or arbitration credits a withdrawal balance. Withdraw it to your connected wallet in a separate transaction.</p><button className="btn-gold" disabled={!q.data||tx.sending||tx.confirming} onClick={()=>tx.send({address:addresses.agentMarket,abi:agentMarketV2Abi,functionName:'withdraw',args:[address]})}>Withdraw to my wallet</button><TxStatus {...tx}/></section>}
export function MarketSettlement({id,t}:{id:bigint;t:{buyer:string;worker:string;arbitrator:string;status:number;payment:bigint;reviewUntil:bigint}}){const {address}=useAccount();const {addresses}=useContracts();const tx=useTx();const [evidence,setEvidence]=useState('');const [amount,setAmount]=useState('');const [error,setError]=useState('');const buyer=address?.toLowerCase()===t.buyer.toLowerCase();const worker=address?.toLowerCase()===t.worker.toLowerCase();const arbitrator=address?.toLowerCase()===t.arbitrator.toLowerCase();const busy=tx.sending||tx.confirming;
 async function send(name:'dispute'|'resolve'|'concede'){setError('');try{const args=name==='dispute'?[id,keccak256(toHex(evidence))]:name==='resolve'?[id,ethInput(amount)]:[id];if(name==='resolve'&&ethInput(amount)>t.payment)throw Error('Worker amount cannot exceed escrow.');await tx.send({address:addresses.agentMarket,abi:agentMarketV2Abi,functionName:name,args});}catch(e){setError((e as Error).message);}}
 return <section className="mt-5 space-y-3 text-sm"><p className="break-all">Agreed arbitrator: {t.arbitrator}</p>{t.reviewUntil>0n&&<p>Review ends: {new Date(Number(t.reviewUntil)*1000).toLocaleString()}</p>}{t.status===2&&buyer&&Date.now()/1000<Number(t.reviewUntil)&&<><label className="block">Dispute evidence<textarea className="input mt-2" value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><p className="text-dim">Only its hash is recorded. Retain the evidence and share it with the arbitrator separately.</p><button className="btn-danger" disabled={busy||!evidence.trim()} onClick={()=>send('dispute')}>Dispute delivery</button></>}{t.status===3&&<><p className="notice">The agreed arbitrator determines the split. There is no automatic timeout settlement; either party can also concede all escrow to the other.</p>{arbitrator&&<><label className="block">Worker award (ETH)<input className="input mt-2" value={amount} onChange={e=>setAmount(e.target.value)}/></label><p>The buyer receives the remainder of {formatEther(t.payment)} ETH.</p><button className="btn-gold" disabled={busy||!amount} onClick={()=>send('resolve')}>Review settlement split</button></>}{(buyer||worker)&&<button className="btn-danger" disabled={busy} onClick={()=>send('concede')}>Concede all escrow to {buyer?'worker':'buyer'}</button>}</>}{error&&<p role="alert" className="text-blood">{error}</p>}<TxStatus {...tx}/></section>;
}
