"use client";
import {useState,useEffect} from 'react';
import {useAccount,usePublicClient} from 'wagmi';
import {decodeEventLog,formatEther,type Hex} from 'viem';
import {contracts,legacyContracts} from '@/lib/config';
import {agentPassportAbi} from '@/lib/abis';
import {positiveId} from '@/lib/validation';
import {actionId} from '@/lib/message';
import {useTx} from '@/lib/tx';
import {TxStatus} from './TxStatus';
type Plan={legacyId:bigint;agent:Hex;purpose:string;validFrom:bigint;validUntil:bigint;perTxLimit:bigint;dailyLimit:bigint;parentId:bigint;actions:Hex[];labels:string[]};
export function MigrationAssistant(){const {address}=useAccount();const client=usePublicClient({chainId:4663});const tx=useTx();const [id,setId]=useState('');const [actions,setActions]=useState('BOOK_TRAVEL, HIRE_AGENTS, PERFORM_WORK, READ_CHAIN, RUN_AGENT');const [parent,setParent]=useState('');const [plan,setPlan]=useState<Plan>();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [newId,setNewId]=useState('');const [accepted,setAccepted]=useState(false);
 useEffect(()=>{if(!tx.confirmed||!tx.hash||!client)return;client.getTransactionReceipt({hash:tx.hash}).then(r=>{for(const log of r.logs){if(log.address.toLowerCase()!==contracts[4663].agentPassport.toLowerCase())continue;try{const e=decodeEventLog({abi:agentPassportAbi,data:log.data,topics:log.topics});if(e.eventName==='PassportMinted')setNewId(String(e.args.passportId));}catch{}}}).catch(()=>setMessage('Confirmed, but unable to read the new ID. Check Registry.'));},[tx.confirmed,tx.hash,client]);
 async function inspect(){setBusy(true);setPlan(undefined);setNewId('');setAccepted(false);setMessage('');try{if(!client||!address)throw Error('Connect the legacy controller wallet.');const legacyId=positiveId(id);const blockNumber=await client.getBlockNumber();const base={address:legacyContracts.agentPassport,abi:agentPassportAbi,blockNumber} as const;const [p,owner,active]=await Promise.all([client.readContract({...base,functionName:'getPassport',args:[legacyId]}),client.readContract({...base,functionName:'ownerOf',args:[legacyId]}),client.readContract({...base,functionName:'isActive',args:[legacyId]})]);if(owner.toLowerCase()!==address.toLowerCase())throw Error('Only the current V1 controller can prepare this replacement.');if(!active||p.status!==0)throw Error('Inactive, expired, or revoked V1 passports are not copied. Review and issue a new identity explicitly.');const labels=[...new Set(actions.split(',').map(x=>x.trim()).filter(Boolean))];if(!labels.length||labels.length>32)throw Error('Enter between 1 and 32 candidate permissions.');const allowed=await Promise.all(labels.map(label=>client.readContract({...base,functionName:'hasPermission',args:[legacyId,actionId(label)]})));const kept=labels.filter((_,i)=>allowed[i]);setPlan({legacyId,agent:p.agent,purpose:p.purpose,validFrom:p.validFrom,validUntil:p.validUntil,perTxLimit:p.perTxLimit,dailyLimit:p.dailyLimit,parentId:p.parentId,labels:kept,actions:kept.map(actionId)});}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function migrate(){if(!plan||!client||!address||!accepted)return;setBusy(true);setMessage('');try{const [owner,p,active]=await Promise.all([client.readContract({address:legacyContracts.agentPassport,abi:agentPassportAbi,functionName:'ownerOf',args:[plan.legacyId]}),client.readContract({address:legacyContracts.agentPassport,abi:agentPassportAbi,functionName:'getPassport',args:[plan.legacyId]}),client.readContract({address:legacyContracts.agentPassport,abi:agentPassportAbi,functionName:'isActive',args:[plan.legacyId]})]);if(owner.toLowerCase()!==address.toLowerCase()||!active||p.status!==0||p.agent!==plan.agent||p.purpose!==plan.purpose||p.perTxLimit!==plan.perTxLimit||p.dailyLimit!==plan.dailyLimit||p.validUntil!==plan.validUntil)throw Error('Legacy state changed. Inspect again.');for(const a of plan.actions)if(!await client.readContract({address:legacyContracts.agentPassport,abi:agentPassportAbi,functionName:'hasPermission',args:[plan.legacyId,a]}))throw Error('Legacy permissions changed. Inspect again.');if(plan.parentId>0n){await tx.send({address:contracts[4663].agentPassport,abi:agentPassportAbi,functionName:'delegate',args:[positiveId(parent),plan.agent,plan.purpose,plan.actions,plan.perTxLimit,plan.dailyLimit,plan.validUntil]});}else await tx.send({address:contracts[4663].agentPassport,abi:agentPassportAbi,functionName:'mint',args:[plan.agent,plan.purpose,plan.validFrom,plan.validUntil,plan.perTxLimit,plan.dailyLimit,plan.actions]});}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel p-6 space-y-4"><h2 className="font-display text-2xl">Prepare a V1 replacement</h2><p className="text-dim">Read an active legacy passport, review its settings, and create the V2 replacement with your wallet. No balance, escrow, or consumer approvals are transferred.</p><label className="block">V1 passport ID<input className="input mt-2" value={id} onChange={e=>{setId(e.target.value);setPlan(undefined);}}/></label><label className="block">Candidate permissions, comma-separated<textarea className="input mt-2" value={actions} onChange={e=>{setActions(e.target.value);setPlan(undefined);}}/></label><p className="text-sm text-dim">V1 cannot enumerate permission names. Include custom action names or bytes32 hashes; only permissions confirmed on V1 are copied. This list may be incomplete.</p><button className="btn-ghost" disabled={busy||tx.sending||tx.confirming} onClick={inspect}>Read V1 and preview</button>{plan&&<><p className="break-all">Agent: {plan.agent}</p><p>Purpose: {plan.purpose}</p><p>Per transaction: {formatEther(plan.perTxLimit)} ETH · Daily: {formatEther(plan.dailyLimit)} ETH (zero means unlimited)</p><p>Expires: {new Date(Number(plan.validUntil)*1000).toLocaleString()}</p><p>Permissions: {plan.labels.join(', ')||'None from the supplied list'}</p>{plan.parentId>0n&&<label className="block">Replacement V2 parent ID for V1 parent #{String(plan.parentId)}<input className="input mt-2" value={parent} onChange={e=>setParent(e.target.value)}/><span className="text-sm text-dim">Migrate the parent first. V2 enforces its permissions, limits, and ownership; this child is never converted to an unrestricted root.</span></label>}<label className="flex gap-3"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I reviewed these replacement settings and understand V1 remains unchanged. This is a new V2 identity, not an atomic cross-contract transfer.</span></label><button className="btn-gold" disabled={!accepted||busy||tx.sending||tx.confirming||!!newId} onClick={migrate}>Review & create V2 replacement</button></>}{newId&&<a className="btn-gold" href={'/passport/'+newId}>Open V2 passport #{newId} and authorize integrations</a>}{message&&<p role="status">{message}</p>}<TxStatus {...tx}/></section>;
}
