"use client";
import {useEffect,useState} from 'react';
import {usePublicClient} from 'wagmi';
import {useQuery} from '@tanstack/react-query';
import {parseAbiItem,formatEther} from 'viem';
import {useContracts} from '@/lib/hooks';
import {explorerTx} from '@/lib/config';
const event=parseAbiItem('event ActionVerified(uint256 indexed passportId,address indexed consumer,bytes32 indexed action,uint256 amount,bytes32 actionHash)');
export function PassportHistory({id}:{id:bigint}){const {chainId,addresses}=useContracts();const client=usePublicClient({chainId});const [end,setEnd]=useState<bigint|null>(null);useEffect(()=>setEnd(null),[chainId,id]);const q=useQuery({queryKey:['passport-history',chainId,String(id),String(end)],enabled:!!client,queryFn:async()=>{if(!client)throw Error('Network unavailable');const to=end??await client.getBlockNumber();const from=to>1999n?to-1999n:0n;const logs=await client.getLogs({address:addresses.agentPassport,event,args:{passportId:id},fromBlock:from,toBlock:to});return {from,to,logs:logs.reverse()};}});
 return <section className="panel p-6 mt-6"><h2 className="font-display text-2xl">Recorded actions</h2><p className="mt-3 text-dim text-sm">History is shown in 2,000-block windows. Records identify the calling consumer; they do not alone prove agent authentication.</p>{q.isPending&&<p className="mt-5">Loading records…</p>}{q.isError&&<p role="alert" className="text-blood mt-5">Unable to read history. <button onClick={()=>q.refetch()}>Retry</button></p>}{q.data&&<><p className="text-sm text-dim mt-4">Blocks {String(q.data.from)}–{String(q.data.to)}</p>{q.data.logs.length===0&&<p className="mt-5 text-dim">No recorded actions in this window.</p>}<div className="space-y-4 mt-5">{q.data.logs.map(l=><div className="border-t border-line pt-3 text-sm" key={l.transactionHash+':'+l.logIndex}><p className="break-all">Consumer: {l.args.consumer}</p><p className="break-all text-dim mt-2">Action: {l.args.action}</p><p className="mt-2">{formatEther(l.args.amount??0n)} ETH · <a className="text-gold" href={explorerTx(chainId,l.transactionHash)} target="_blank" rel="noreferrer">Transaction ↗</a></p></div>)}</div><div className="flex flex-wrap gap-3 mt-5"><button className="btn-ghost" disabled={q.data.from===0n||q.isFetching} onClick={()=>setEnd(q.data!.from-1n)}>Earlier blocks</button><button className="btn-ghost" onClick={()=>{setEnd(null);void q.refetch();}} disabled={q.isFetching}>Latest</button></div></>}</section>;
}